Repository RandomStranger18/python-pipeline, pull requests merged in 2022-10, with the labels that each got.

#2 Added recursive functionality
  Binary Search/Binary Search.py
Labels: enhancement, hactoberfest, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#3 Updated logo in README.md
  README.md
Labels: documentation, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#7 Create sparks.py
  spark_particles/sparks.py
Labels: enhancement, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#8 Bug fixed
  Binary Search/Binary Search.py
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED, bug fix

#9 Create Dice.py
  Dice.py
Labels: enhancement, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#11 Added img to cartoon converter
  img to cartoon.py
Labels: good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#12 Linear Search
  Linear Serch.py
Labels: enhancement, good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#14 Create bubble_sort.py
  bubble_sort.py
Labels: good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#13 Create binary_tree.py
  binary_tree.py
Labels: enhancement, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#18 Deleting a Node in a Linked List.
  Deleting a Node.py
Labels: enhancement, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#17 Postorder Traversal
  Postorder Traversal.py
Labels: HACKTOBERFEST, HACKTOBERFEST-ACCEPTED
